[package]
name = "nn_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.9.0-alpha.1"
log = "0.4.21"
csv = "1.3.0"
datetime = "0.5.2"
savefile = "0.17.4"
savefile-derive = "0.17.4"
